import { useEffect, useMemo, useState } from "react";
import { Search, UserRound, Users, X } from "lucide-react";
import DashboardLayout from "@/components/layouts/DashboardLayout";
import { EmptyState, LoadingSkeleton, PageHeader, Panel, StatCard, StatusBadge } from "@/components/recruitment/EnterpriseUi";
import { getApplications } from "@/services/applicationService";

const tones = { Pending: "amber", Screening: "blue", Shortlisted: "violet", Interview: "cyan", Offer: "amber", Hired: "green", Rejected: "red" };

function CandidateDrawer({ candidate, onClose }) {
  if (!candidate) return null;
  return <><button type="button" onClick={onClose} className="fixed inset-0 z-40 bg-slate-950/75 backdrop-blur-sm" aria-label="Close candidate details" /><aside className="fixed inset-y-0 right-0 z-50 w-full max-w-xl overflow-y-auto border-l border-slate-800 bg-[#07101f] shadow-2xl"><div className="flex items-center justify-between border-b border-slate-800 px-6 py-5"><div><p className="text-sm font-medium text-cyan-300">Candidate profile</p><h2 className="mt-1 text-lg font-semibold text-white">{candidate.full_name}</h2></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800"><X size={19} /></button></div><div className="space-y-6 p-6"><Panel className="p-5"><p className="text-sm text-slate-500">Contact</p><p className="mt-2 text-slate-200">{candidate.email}</p><p className="mt-1 text-sm capitalize text-slate-500">{candidate.role}</p></Panel><Panel className="p-5"><h3 className="font-medium text-white">Application history</h3><div className="mt-4 space-y-4">{candidate.applications.map((app) => <div key={app.id} className="flex items-center justify-between gap-4 border-b border-slate-800 pb-4 last:border-0 last:pb-0"><div><p className="text-sm text-slate-200">{app.job.title}</p><p className="mt-1 text-xs text-slate-500">{app.job.company} · {app.job.location}</p></div><StatusBadge tone={tones[app.status] || "slate"}>{app.status}</StatusBadge></div>)}</div></Panel></div></aside></>;
}

function Candidates() {
  const [applications, setApplications] = useState([]); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState("");
  useEffect(() => { getApplications().then((data) => setApplications(Array.isArray(data) ? data : [])).catch((err) => { console.error(err); setError("Unable to load candidates from the server."); }).finally(() => setLoading(false)); }, []);
  const candidates = useMemo(() => { const map = new Map(); applications.forEach((app) => { if (!app.user) return; const current = map.get(app.user.id) || { ...app.user, applications: [] }; current.applications.push(app); map.set(app.user.id, current); }); return [...map.values()]; }, [applications]);
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return q ? candidates.filter((c) => [c.full_name, c.email, ...c.applications.flatMap((a) => [a.job?.title, a.job?.company, a.status])].filter(Boolean).some((v) => String(v).toLowerCase().includes(q))) : candidates; }, [candidates, search]);
  const interview = candidates.filter((c) => c.applications.some((a) => a.status === "Interview")).length; const hired = candidates.filter((c) => c.applications.some((a) => a.status === "Hired")).length;
  return <DashboardLayout><PageHeader eyebrow="Talent workspace" title="Candidates" subtitle="Review real candidates and their application history." /><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total candidates" value={candidates.length} detail="Unique applicants" icon={Users} /><StatCard label="Applications" value={applications.length} detail="Across all candidates" icon={UserRound} tone="bg-blue-400/10 text-blue-300" /><StatCard label="In interview" value={interview} detail="Candidates at interview stage" icon={Users} tone="bg-violet-400/10 text-violet-300" /><StatCard label="Hired" value={hired} detail="Successful candidates" icon={UserRound} tone="bg-emerald-400/10 text-emerald-300" /></div><Panel className="mt-6 overflow-hidden"><div className="border-b border-slate-800 p-4"><div className="relative w-full lg:max-w-sm"><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-500" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search candidates..." className="h-10 w-full rounded-lg border border-slate-800 bg-slate-950/40 pl-10 pr-4 text-sm text-slate-200 outline-none placeholder:text-slate-600 focus:border-cyan-400/50" /></div></div>{loading ? <LoadingSkeleton rows={5} /> : error ? <EmptyState title="Unable to load candidates" description={error} /> : filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-800 bg-slate-950/25 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-3.5">Candidate</th><th className="px-4 py-3.5">Applications</th><th className="px-4 py-3.5">Latest job</th><th className="px-4 py-3.5">Status</th><th className="px-6 py-3.5 text-right">Actions</th></tr></thead><tbody>{filtered.map((candidate) => { const latest = candidate.applications[0]; return <tr key={candidate.id} className="border-b border-slate-800/70 hover:bg-slate-800/25"><td className="px-6 py-4"><p className="font-medium text-slate-200">{candidate.full_name}</p><p className="mt-0.5 text-xs text-slate-500">{candidate.email}</p></td><td className="px-4 py-4 text-slate-400">{candidate.applications.length}</td><td className="px-4 py-4 text-slate-300">{latest?.job?.title || "—"}</td><td className="px-4 py-4"><StatusBadge tone={tones[latest?.status] || "slate"}>{latest?.status || "—"}</StatusBadge></td><td className="px-6 py-4 text-right"><button type="button" onClick={() => setSelected(candidate)} className="rounded-lg px-3 py-2 text-xs font-medium text-cyan-300 hover:bg-cyan-400/10">View</button></td></tr>; })}</tbody></table></div> : <EmptyState title={search ? "No matching candidates" : "No candidates found"} description="Candidates appear after they apply to a job." />}</Panel><CandidateDrawer candidate={selected} onClose={() => setSelected(null)} /></DashboardLayout>;
}
export default Candidates;
