import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Mail } from "lucide-react";
import AuthLayout from "@/components/layouts/AuthLayout";
import Logo from "@/components/ui/Logo";
import { requestPasswordReset } from "@/services/passwordService";

function ForgotPassword() {
  const [email, setEmail] = useState(""); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(""); try { await requestPasswordReset(email); setMessage("If an account exists for this email, reset instructions have been sent."); } catch (err) { setError(err.response?.status === 404 ? "Password recovery is not available yet. The backend endpoint still needs to be implemented." : err.response?.data?.detail || "We couldn’t start password recovery. Please try again."); } finally { setLoading(false); } };
  return <AuthLayout><section className="w-full max-w-md rounded-2xl border border-slate-700/80 bg-slate-900/75 p-6 shadow-2xl shadow-black/30 backdrop-blur-xl sm:p-8"><Logo /><p className="mt-8 text-sm font-medium text-cyan-300">Account recovery</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Reset your password</h1><p className="mt-2 text-sm leading-6 text-slate-400">Enter your work email and we&apos;ll send secure reset instructions.</p>{message ? <div className="mt-7 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm text-emerald-200">{message}</div> : <form className="mt-7 space-y-5" onSubmit={submit}><label htmlFor="recovery-email" className="block text-sm font-medium text-slate-300">Work email</label><div className="relative"><Mail size={18} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" /><input id="recovery-email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@company.com" required className="h-12 w-full rounded-xl border border-slate-700/90 bg-slate-950/55 pl-12 pr-4 text-sm text-white outline-none placeholder:text-slate-600 focus:border-cyan-400/50 focus:ring-2 focus:ring-cyan-400/10" /></div>{error && <p role="alert" className="rounded-xl border border-red-400/15 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<button disabled={loading} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-cyan-400 text-sm font-semibold text-slate-950 hover:bg-cyan-300 disabled:opacity-60">{loading ? "Sending..." : "Send reset instructions"}<ArrowRight size={16} /></button></form>}<Link to="/login" className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-slate-400 hover:text-cyan-300"><ArrowLeft size={16} />Back to sign in</Link></section></AuthLayout>;
}
export default ForgotPassword;
