import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowLeft, CheckCircle2, Lock } from "lucide-react";
import AuthLayout from "@/components/layouts/AuthLayout";
import Logo from "@/components/ui/Logo";
import { resetPassword } from "@/services/passwordService";

function ResetPassword() {
  const [params] = useSearchParams(); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(false);
  const submit = async (event) => { event.preventDefault(); if (password !== confirmPassword) { setError("Passwords do not match."); return; } setLoading(true); setError(""); try { await resetPassword({ token: params.get("token"), password }); setSuccess(true); } catch (err) { setError(err.response?.status === 404 ? "Password reset is not available yet. The backend endpoint still needs to be implemented." : err.response?.data?.detail || "We couldn't reset your password. Please try again."); } finally { setLoading(false); } };
  return <AuthLayout><section className="w-full max-w-md rounded-2xl border border-slate-700/80 bg-slate-900/75 p-6 shadow-2xl shadow-black/30 backdrop-blur-xl sm:p-8"><Logo /><p className="mt-8 text-sm font-medium text-cyan-300">Choose a new password</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Secure your account</h1><p className="mt-2 text-sm leading-6 text-slate-400">Use at least eight characters and do not reuse a previous password.</p>{success ? <div className="mt-7 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm text-emerald-200"><CheckCircle2 className="mb-2" size={20} />Password updated. You can now sign in.</div> : <form className="mt-7 space-y-5" onSubmit={submit}>{[["new-password", "New password", password, setPassword], ["confirm-password", "Confirm password", confirmPassword, setConfirmPassword]].map(([id, label, value, setValue]) => <div key={id}><label htmlFor={id} className="mb-2 block text-sm font-medium text-slate-300">{label}</label><div className="relative"><Lock size={18} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" /><input id={id} type="password" autoComplete={id === "new-password" ? "new-password" : "new-password"} minLength="8" value={value} onChange={(event) => setValue(event.target.value)} required className="h-12 w-full rounded-xl border border-slate-700/90 bg-slate-950/55 pl-12 pr-4 text-sm text-white outline-none focus:border-cyan-400/50 focus:ring-2 focus:ring-cyan-400/10" /></div></div>)}{error && <p role="alert" className="rounded-xl border border-red-400/15 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<button disabled={loading} className="h-12 w-full rounded-xl bg-cyan-400 text-sm font-semibold text-slate-950 hover:bg-cyan-300 disabled:opacity-60">{loading ? "Updating..." : "Update password"}</button></form>}<Link to="/login" className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-slate-400 hover:text-cyan-300"><ArrowLeft size={16} />Back to sign in</Link></section></AuthLayout>;
}
export default ResetPassword;
