"""create_resume_analysis_table

Revision ID: 2210bf5c4794
Revises: 31219632e1a5
Create Date: 2026-07-16 00:44:16.545269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2210bf5c4794'
down_revision: Union[str, Sequence[str], None] = '31219632e1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('detected_skills', sa.Text(), nullable=True),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.String(length=50), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('projects', sa.Text(), nullable=True),
    sa.Column('analysis_status', sa.String(length=30), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id')
    )
    op.create_index(op.f('ix_resume_analysis_id'), 'resume_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_analysis_id'), table_name='resume_analysis')
    op.drop_table('resume_analysis')
    # ### end Alembic commands ###
